FROM cycbercompany/workspace-node:latest
WORKDIR /app
COPY release-artifacts/node/ /opt/cycbercompany-node/
RUN mkdir -p /workspace /root/.cycbercompany-node/data
VOLUME ["/workspace", "/root/.cycbercompany-node"]
