package io.github.yourname.agentstudio.orchestration;

public enum RunEventType {
    RUN_QUEUED,
    SKILLS_RESOLVED,
    RUN_SPEC_RESOLVED,
    RUN_STARTED,
    STEP_STARTED,
    RETRIEVAL_COMPLETED,
    RETRIEVAL_SOURCES,
    MODEL_RATE_LIMITED,
    TOOL_CALL_REQUESTED,
    TOOL_CALL_STARTED,
    TOOL_APPROVAL_REQUIRED,
    TOOL_CALL_COMPLETED,
    TOOL_BUDGET_WARNING,
    RUN_WAITING_APPROVAL,
    RUN_RESUMED,
    TOOL_CALL_FAILED,
    TOKEN_DELTA,
    STEP_COMPLETED,
    RUN_NEEDS_VERIFICATION,
    FINAL_ANSWER,
    RUN_FAILED,
    RUN_CANCELLED
}
